language: scala

scala:
   - 2.12.4

sudo: false

jdk:
   - oraclejdk8

branches:
  except:
    - gh-pages

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xms1024M fastOptJS test dist

scripts:
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy-to-gh-pages.sh
  on:
    tags: true